✨Heuristic mapper fidelity preparation
cda-tum/qmap pull request #204
Opened 2022-12-17 03:35 UTC by EliasLF

## Description

- isolated the heuristic to HeuristicMapper::Node::updateHeuristicCost for less redundant code and easier expansion with further heuristic types (e.g. the planned fidelity aware approach)
- removed redundant field HeuristicMapper::Node::totalCost (redundant to HeuristicMapper::Node::costFixed)
- added consider_fidelity field to configuration classes

Fixes # (issue)

## Checklist:

- [x] The pull request only contains commits that are related to it.
- [x] I have added appropriate tests and documentation.
- [ ] I have made sure that all CI jobs on GitHub pass.
- [ ] The pull request introduces no new warnings and follows the project's style guidelines.

2022-12-23 11:10 UTC, burgholzer requested changes
Sorry that it took so long to get to this.
Overall this LGTM and certainly improves the structure of the code.

Just two minor comments/suggestions before this can be merged.

2022-12-23 11:10 UTC, burgholzer commented on include/heuristic/HeuristicMapper.hpp
> +        }
These two lines can safely be removed in this PR as they do not contribute any functionality. (which is also why GitHub CodeQL is complaining)
```suggestion
```

2022-12-23 11:10 UTC, burgholzer commented on include/heuristic/HeuristicMapper.hpp
> +   *heuristic specified
this addition seems out-of-place.

2022-12-25 08:19 UTC, EliasLF commented
That's right. Those can just be removed. Should be resolved now. Thank you.

2022-12-25 12:59 UTC, burgholzer approved these changes
LGTM 👍🏻

2022-12-25 12:59 UTC, merged